### ISSUE TITLE
🐛 Complimentary plan is sometimes missing

### ISSUE THREAD

**Issue by allouis** [TryGhost/Members#125] opened 2020-02-07 16:17 UTC
In some instances the Complimentary plan is not created, leading to errors when trying to set the plan on a member.

```
    InternalServerError: Cannot read property 'id' of undefined
        at new GhostError (/home/ghost/core/server/lib/common/errors.js:10:26)
        at _private.prepareError (/home/ghost/core/server/web/shared/middlewares/error-handler.js:51:19)
        at Layer.handle_error (/home/ghost/node_modules/express/lib/router/layer.js:71:5)
        at trim_prefix (/home/ghost/node_modules/express/lib/router/index.js:315:13)
        at /home/ghost/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/home/ghost/node_modules/express/lib/router/index.js:335:12)
        at next (/home/ghost/node_modules/express/lib/router/index.js:275:10)
        at Layer.handle_error (/home/ghost/node_modules/express/lib/router/layer.js:67:12)
        at trim_prefix (/home/ghost/node_modules/express/lib/router/index.js:315:13)
        at /home/ghost/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/home/ghost/node_modules/express/lib/router/index.js:335:12)
        at next (/home/ghost/node_modules/express/lib/router/index.js:275:10)
        at Layer.handle_error (/home/ghost/node_modules/express/lib/router/layer.js:67:12)
        at trim_prefix (/home/ghost/node_modules/express/lib/router/index.js:315:13)
        at /home/ghost/node_modules/express/lib/router/index.js:284:7
        at Function.process_params (/home/ghost/node_modules/express/lib/router/index.js:335:12)
        at next (/home/ghost/node_modules/express/lib/router/index.js:275:10)
        at /home/ghost/node_modules/express/lib/router/index.js:635:15
        at next (/home/ghost/node_modules/express/lib/router/index.js:260:14)
        at next (/home/ghost/node_modules/express/lib/router/route.js:127:14)
        at apiImpl.then.then.catch (/home/ghost/core/server/api/shared/http.js:95:17)
        at tryCatcher (/home/ghost/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/home/ghost/node_modules/bluebird/js/release/promise.js:547:31)
        at Promise._settlePromise (/home/ghost/node_modules/bluebird/js/release/promise.js:604:18)
        at Promise._settlePromise0 (/home/ghost/node_modules/bluebird/js/release/promise.js:649:10)
        at Promise._settlePromises (/home/ghost/node_modules/bluebird/js/release/promise.js:725:18)
        at _drainQueueStep (/home/ghost/node_modules/bluebird/js/release/async.js:93:12)
        at _drainQueue (/home/ghost/node_modules/bluebird/js/release/async.js:86:9)
        at Async._drainQueues (/home/ghost/node_modules/bluebird/js/release/async.js:102:5)
        at Immediate.Async.drainQueues [as _onImmediate] (/home/ghost/node_modules/bluebird/js/release/async.js:15:14)
        at runCallback (timers.js:705:18)
        at tryOnImmediate (timers.js:676:5)
        at processImmediate (timers.js:658:5)
        at process.topLevelDomainCallback (domain.js:126:23)

    TypeError: Cannot read property 'id' of undefined
        at StripePaymentProcessor.setComplimentarySubscription (/home/ghost/node_modules/@tryghost/members-api/lib/stripe/index.js:205:45)
```

**Comment by shriker** [comment] 2020-02-08 23:46
I ran into this one today. I believe it's caused by having monthly/yearly plans for $0.00 that _already exist_ in Stripe. This can easily happen if you set your subscription prices to 0 on initial subscription setup.

A solution is to go to Stripe and delete any pricing plans that are set to $0.00 and do not have the "Complimentary" name. https://dashboard.stripe.com/subscriptions/products

Once removed, the Complimentary plan ought to be able to re-create itself properly.

**Comment by gargol** [comment] 2020-02-11 09:23
@shriker I think this commit should fix the problem - https://github.com/TryGhost/Ghost/commit/51c2b22e9fbec4bf5dc2f29a4b7323a5d95afbd3, it had to do with an issue that was somewhat related but not particularly on "Members" level :thinking: And just realized after pushing it out that it might be solving this issue as well :thinking:

**Comment by gargol** [comment] 2020-02-11 09:24
Will close this issue for now, but feel free to ping if you encounter it again or think it should be solved in a different way

**Closed by gargol** 2020-02-11 09:24 UTC
Labels: bug
